[package]
name = "browser-jr"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "browser_jr"
path = "src/lib.rs"

[[bin]]
name = "browser-jr"
path = "src/main.rs"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
html5ever = "0.39.0"
http = "1.5.0"
ureq = { version = "3.4.0", default-features = false }
